[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["cd ai-backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd ai-backend && python app.py"
