[build]
builder = "NIXPACKS"
buildCommand = "cd ai-backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd ai-backend && python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
