import { useState } from 'react';
import { Plane, Wind, Gauge, Zap, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import DragCalculator from '../components/DragCalculator';

export default function PlaneMechanicsPage() {
  const [activeTab, setActiveTab] = useState('aerodynamics');
  const navigate = useNavigate();

  const tabs = [
    { id: 'aerodynamics', label: 'Aerodynamics', icon: Wind },
    { id: 'engines', label: 'Jet Engines', icon: Zap },
    { id: 'flight', label: 'Flight Controls', icon: Gauge },
    { id: 'systems', label: 'Aircraft Systems', icon: Plane },
  ];

  const content = {
    aerodynamics: {
      title: 'Aircraft Aerodynamics',
      sections: [
        {
          title: 'Four Forces of Flight',
          content: `Every aircraft in flight experiences four fundamental forces:

Lift:
• Upward force generated by wings
• Created by pressure difference (Bernoulli's principle)
• Increases with speed and angle of attack
• Must overcome weight for flight

Weight:
• Downward force due to gravity
• Acts through center of gravity
• Reduced by using lightweight materials
• Constant unless fuel is burned

Thrust:
• Forward force from engines
• Overcomes drag to maintain speed
• Can be increased for acceleration/climb
• Provided by propellers or jet engines

Drag:
• Resistance to motion through air
• Increases with speed (squared relationship)
• Minimized through streamlined design
• Two types: parasitic and induced`,
        },
        {
          title: 'Wing Design & Airfoils',
          content: `Wings are the heart of aircraft design:

Airfoil Shape:
• Curved upper surface, flatter lower surface
• Creates pressure difference for lift
• Camber: curvature of the airfoil
• Thickness ratio affects performance

Wing Characteristics:
• Aspect Ratio: wingspan² / wing area
• High aspect ratio = efficient (gliders)
• Low aspect ratio = maneuverable (fighters)
• Sweep angle affects high-speed performance

Lift Equation: L = ½ × ρ × v² × S × CL

Where:
• ρ = air density
• v = velocity
• S = wing area
• CL = lift coefficient`,
        },
        {
          title: 'Angle of Attack & Stalls',
          content: `Understanding the critical angle:

Angle of Attack (AoA):
• Angle between wing chord and airflow
• Increasing AoA increases lift... to a point
• Critical angle: typically 15-20 degrees
• Beyond critical angle: stall occurs

Stall Characteristics:
• Airflow separates from wing surface
• Sudden loss of lift
• Increase in drag
• Aircraft begins to descend
• Recoverable by reducing AoA

Stall Prevention:
• Maintain adequate airspeed
• Avoid excessive pitch angles
• Use stall warning systems
• Practice stall recovery procedures
• Wing design features (vortex generators, slots)`,
        },
      ],
    },
    engines: {
      title: 'Jet Engine Technology',
      sections: [
        {
          title: 'How Jet Engines Work',
          content: `Jet engines operate on Newton's Third Law:

Basic Principle:
• Suck in air at the front
• Compress it to high pressure
• Add fuel and ignite
• Hot gases expand and exit at high speed
• Reaction force propels aircraft forward

Four Main Sections:
1. Intake: Captures and slows incoming air
2. Compressor: Increases air pressure (10-40x)
3. Combustion Chamber: Burns fuel at 2000°C+
4. Turbine: Extracts energy to drive compressor

Exhaust: Remaining energy creates thrust`,
        },
        {
          title: 'Types of Jet Engines',
          content: `Different designs for different missions:

Turbojet:
• Simple, pure jet engine
• All thrust from exhaust
• Very high speed capability
• Loud and fuel-inefficient
• Used in early jets and missiles

Turbofan:
• Large fan at front
• Most thrust from fan (bypass air)
• Quieter and more efficient
• Used in modern airliners
• Bypass ratio: 5:1 to 12:1

Turboprop:
• Turbine drives propeller
• Efficient at lower speeds
• Used in regional aircraft
• Good for short runways
• Combines jet and propeller benefits

Turboshaft:
• Powers helicopter rotors
• All power to shaft, no jet thrust
• Compact and powerful
• Used in helicopters and some boats`,
        },
        {
          title: 'Thrust & Performance',
          content: `Understanding engine power:

Thrust Measurement:
• Measured in pounds (lbf) or Newtons (N)
• Commercial engines: 20,000-100,000+ lbf
• Fighter jets: 15,000-35,000 lbf per engine
• Thrust-to-weight ratio critical for fighters

Factors Affecting Thrust:
• Air density (altitude, temperature)
• Airspeed (ram effect)
• Engine RPM (N1, N2 speeds)
• Throttle setting

Specific Fuel Consumption:
• Fuel burned per unit of thrust
• Modern turbofans: 0.5-0.6 lb/lbf/hr
• Efficiency improves with bypass ratio
• Cruise altitude optimization important`,
        },
      ],
    },
    flight: {
      title: 'Flight Control Systems',
      sections: [
        {
          title: 'Primary Flight Controls',
          content: `Three axes of aircraft control:

Pitch (Nose Up/Down):
• Controlled by elevators on tail
• Pull stick back = nose up
• Push stick forward = nose down
• Affects climb/descent rate
• Stabilator on some aircraft

Roll (Banking):
• Controlled by ailerons on wings
• Left aileron up, right down = roll right
• Used for turning
• Spoilers assist on large aircraft
• Differential ailerons reduce adverse yaw

Yaw (Nose Left/Right):
• Controlled by rudder on tail
• Coordinates with roll in turns
• Counteracts adverse yaw
• Used for crosswind landings
• Less used in normal flight`,
        },
        {
          title: 'Secondary Flight Controls',
          content: `Additional surfaces for performance:

Flaps:
• Extend from trailing edge of wing
• Increase lift and drag
• Allow slower landing speeds
• Multiple positions (0°, 10°, 20°, 30°, 40°)
• Retracted for cruise efficiency

Slats:
• Extend from leading edge
• Delay stall at high angles
• Used with flaps for takeoff/landing
• Automatic on many aircraft
• Increase maximum lift coefficient

Spoilers/Speed Brakes:
• Panels that rise from wing
• Reduce lift, increase drag
• Used for descent and landing
• Ground spoilers after touchdown
• Help with rapid deceleration

Trim Systems:
• Fine-tune control surface position
• Reduce pilot workload
• Maintain desired attitude
• Electric or manual operation`,
        },
        {
          title: 'Fly-by-Wire Systems',
          content: `Modern computer-controlled flight:

How It Works:
• Pilot inputs go to computers
• Computers interpret commands
• Actuators move control surfaces
• Sensors provide feedback
• No direct mechanical connection

Advantages:
• Envelope protection (prevents dangerous maneuvers)
• Reduced pilot workload
• Optimal control surface coordination
• Weight savings (no heavy cables)
• Easier to implement stability augmentation

Flight Modes:
• Normal Law: Full envelope protection
• Alternate Law: Reduced protections
• Direct Law: Minimal computer intervention
• Used in Airbus, Boeing 777+, F-16, etc.`,
        },
      ],
    },
    systems: {
      title: 'Aircraft Systems',
      sections: [
        {
          title: 'Hydraulic Systems',
          content: `Power for flight controls and more:

Purpose:
• Operate flight control surfaces
• Extend/retract landing gear
• Power brakes
• Operate flaps and slats
• Nose wheel steering

System Components:
• Hydraulic pumps (engine-driven)
• Reservoirs for fluid storage
• Actuators for movement
• Pressure: typically 3000 PSI
• Multiple independent systems for redundancy

Backup Systems:
• Electric pumps
• Ram Air Turbine (RAT)
• Manual reversion (small aircraft)
• Accumulator for emergency use`,
        },
        {
          title: 'Pressurization & Oxygen',
          content: `Keeping passengers comfortable at altitude:

Cabin Pressurization:
• Maintains comfortable pressure at altitude
• Typical cabin altitude: 6,000-8,000 ft
• Actual altitude: 35,000-43,000 ft
• Bleed air from engines
• Outflow valves control pressure

Why It's Needed:
• Insufficient oxygen above 10,000 ft
• Hypoxia risk without pressurization
• Decompression sickness prevention
• Passenger comfort

Emergency Oxygen:
• Drop-down masks for passengers
• 12-15 minutes of oxygen
• Enough time to descend to safe altitude
• Crew has separate oxygen system
• Portable bottles for crew use`,
        },
        {
          title: 'Avionics & Navigation',
          content: `Modern aircraft electronics:

Flight Instruments:
• Primary Flight Display (PFD)
• Navigation Display (ND)
• Engine Indication and Crew Alerting System (EICAS)
• Glass cockpit replaces analog gauges
• Heads-Up Display (HUD) in advanced aircraft

Navigation Systems:
• GPS: Global Positioning System
• ILS: Instrument Landing System
• VOR: VHF Omnidirectional Range
• DME: Distance Measuring Equipment
• TCAS: Traffic Collision Avoidance System

Autopilot:
• Maintains altitude, heading, speed
• Can fly entire approach and landing
• Reduces pilot workload
• Multiple levels of automation
• Pilot monitoring always required`,
        },
      ],
    },
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-black text-white">
      {/* Header */}
      <div className="border-b border-gray-700 bg-gray-900/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 py-4">
          <div className="flex items-center gap-4">
            <button
              onClick={() => navigate('/')}
              className="p-2 hover:bg-gray-800 rounded-lg transition-colors"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
            <Plane className="w-8 h-8 text-cyan-400" />
            <div>
              <h1 className="text-2xl font-bold">Aircraft Mechanics & Engineering</h1>
              <p className="text-sm text-gray-400">Master the principles of flight and aviation</p>
            </div>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="border-b border-gray-700 bg-gray-900/30 sticky top-[73px] z-10">
        <div className="max-w-7xl mx-auto px-4">
          <div className="flex gap-2 overflow-x-auto">
            {tabs.map((tab) => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex items-center gap-2 px-4 py-3 border-b-2 transition-colors whitespace-nowrap ${
                    activeTab === tab.id
                      ? 'border-cyan-500 text-cyan-400'
                      : 'border-transparent text-gray-400 hover:text-gray-300'
                  }`}
                >
                  <Icon className="w-4 h-4" />
                  <span className="font-medium">{tab.label}</span>
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="space-y-8">
          <div>
            <h2 className="text-3xl font-bold mb-2">{content[activeTab].title}</h2>
            <div className="h-1 w-20 bg-gradient-to-r from-cyan-500 to-blue-500 rounded-full" />
          </div>

          {content[activeTab].sections.map((section, index) => (
            <div
              key={index}
              className="bg-gray-800/50 backdrop-blur border border-gray-700 rounded-xl p-6 hover:border-gray-600 transition-colors"
            >
              <h3 className="text-xl font-semibold mb-4 text-cyan-400">{section.title}</h3>
              <div className="text-gray-300 whitespace-pre-line leading-relaxed">
                {section.content}
              </div>
            </div>
          ))}

          {/* Fun Facts */}
          <div className="bg-gradient-to-r from-cyan-500/10 to-blue-500/10 border border-cyan-500/30 rounded-xl p-6">
            <h3 className="text-xl font-semibold mb-4 flex items-center gap-2">
              <Plane className="w-5 h-5 text-cyan-400" />
              Aviation Facts
            </h3>
            <ul className="space-y-2 text-gray-300">
              <li>• Commercial jets cruise at 500-600 mph (Mach 0.85)</li>
              <li>• A Boeing 747 has 6 million parts</li>
              <li>• Modern jet engines are 80% more efficient than 1960s engines</li>
              <li>• The SR-71 Blackbird could fly at Mach 3.3 (2,200+ mph)</li>
              <li>• Airbus A380 can carry up to 853 passengers</li>
              <li>• Fighter jets can pull 9+ Gs in maneuvers</li>
            </ul>
          </div>

          {/* Interactive Calculator */}
          <div>
            <h2 className="text-3xl font-bold mb-6 flex items-center gap-3">
              <Gauge className="w-8 h-8 text-cyan-400" />
              Interactive Tools
            </h2>
            <DragCalculator />
          </div>
        </div>
      </div>
    </div>
  );
}
